[
  {
    id: 2517,
    name: 'Abror Anvarov',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'abror.anvarov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: true,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 5,
    name: 'Aleksandra Mratinkovic',
    position: 'Recruiter',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/8e/ac/0d074a62e78c0ace3dc94d4fe10518a8745.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'aleksandra.mratinkovic@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 979,
    name: 'Aleksandr Kurhanskyi',
    position: 'Angular Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/c2/30/7b3bee589eee82b366439d2c9651be8d761.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'oleksandr.kurhanskyi@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1124,
    name: 'Aleksandr Savulovskyi',
    position: 'Angular Developer',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/1d/06/cde16216f746bfcb0a02884184a972b6398.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'aleksandr.savulovskyi@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 996,
    name: 'Aleksandr Zhukovskiy',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/5a/a5/7f89b3e449d43d830efc187a4d17d81b586.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'aleksandr.zhukovskiy@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 992,
    name: 'Alexander Lodygin',
    position: 'Angular Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/83/cc/fd40635a54be3545dcb14ae7df0aa341972.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'alexander.lodygin@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 997,
    name: 'Alexandr Gerasimenko',
    position: 'Angular Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/f1/85/f0466490dde639eb8aee82d859c15883131.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'alexandr.gerasimenko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 972,
    name: 'Alexey Belous',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/c7/85/0d68fef88dd7903b52ce735a6707c33b694.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'alexey.belous@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 991,
    name: 'Alina Sukhova',
    position: 'CEO',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/5f/b5/3ab56a6e186ce606b191275cbb0c761f415.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'alina.sukhova@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: true,
  },
  {
    id: 965,
    name: 'Andrey Cherkashin',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'andrey.cherkashin@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 974,
    name: 'Anna Fedosova',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/09/4b/02f7bd1764d966a34d9e19c7cf4ed6e4388.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'anna.fedosova@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 973,
    name: 'Anna Zhukovskaya',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/18/84/2b1710973e5e637ecd8596e94095017d820.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'anna.zhukovskaya@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 980,
    name: 'Anton Belchynskyi',
    position: 'Project Manager',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/a2/e0/fb88e42a4ba48fed910957408441c9b9298.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'anton.belchynskyi@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: true,
  },
  {
    id: 971,
    name: 'Artem Petrov',
    position: 'CFO',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'artem.petrov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: true,
  },
  {
    id: 990,
    name: 'Bohdan Vovchenko',
    position: 'QA',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/be/b5/aeb2c7d054016e55899aff34e2d7fb9a372.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'bohdan.vovchenko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 886,
    name: 'Denys Kravtsov',
    position: 'Laravel Developer',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/cf/6c/21a0c62932c45504d3375996a982b94b591.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'denys.kravtsov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 993,
    name: 'Dima Kotlyarov',
    position: 'Flutter Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/34/b6/ba8c59e5aacfb4a4c51993162eba6b2023.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'dima.kotrlyarov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 994,
    name: 'Dima Popov',
    position: 'QA',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'dmytro.popov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 978,
    name: 'Dima Tkhorik',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'dmytro.tkhorik@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 967,
    name: 'Dmitriy Daniuk',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'dmitriy.daniuk@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1000,
    name: 'Dmitriy Savchenko',
    position: 'Head of Project Manager',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'dmitriy.savchenko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: true,
  },
  {
    id: 3,
    name: 'Ekateryna Sorokvashyna',
    position: 'Recruiter',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/1b/7e/7ca1314eef7a5cb6fba3aef54641637e398.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'ekateryna.sorokvashyna@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 2230,
    name: 'Evgeniy Tsvetikov',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'evgeniy.tsvetikov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1006,
    name: 'Fayyoz Bobokulov',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'fayyoz.bobokulov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 499,
    name: 'Ikramov Saidjamol',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/06/ac/878e6c3e3921caa07c4191f85b05fdb8724.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'saidjamol.ikramov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1001,
    name: 'Kamron Shamsiev',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/24/24/e2c2b717a55c490c6deaa5f0a09f42bb373.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'kamron.shamsiev@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 999,
    name: 'Kateryna Bashtenko',
    position: 'Sales',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'kateryna.bashtenko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: true,
    has_file_access_by_default: true,
  },
  {
    id: 988,
    name: 'Kirill Chernov',
    position: 'Angular dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'kirill.chernov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 2,
    name: 'Kseniia Dziuba',
    position: 'HR manager',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/59/6c/bb027f0a6fa6b4b5752f0bc373535d8b663.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'ksenia.dziuba@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: true,
    has_file_access_by_default: true,
  },
  {
    id: 981,
    name: 'Maksim Ignatchenko',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/19/28/cad991c46a3fdcd0ab9ca07cf04bb280770.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'maksim.ignatchenko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 7,
    name: 'Mamura Mulladjanova',
    position: 'Recruiter',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/49/12/993715222ab415d52c3df6eb8482138a672.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'mamura.mullajanova@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: true,
  },
  {
    id: 989,
    name: 'Mikhail Bodnar',
    position: 'React Native Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/87/93/7a4a21a60d000dd4280504b463d1599e300.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'bodnar.mykhailo@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 977,
    name: 'Mikhail Markevich',
    position: 'PHP Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/1c/5c/239d2b18bf085e45e4d182c7252451d2983.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'mykhailo.markevich@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 995,
    name: 'Nadtoka Dmitry',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'dmitry.nadtoka@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 983,
    name: 'Nikita Riazantsev',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/67/91/72df69f90e3a45e3edeaa10f6572023749.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'nikita.riazantsev@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 970,
    name: 'Nikita Samelyuk',
    position: 'QA',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/b4/64/17465d27b71ffd2c2b2f3a2326370304963.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'nikita.samelyuk@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: true,
    has_file_access_by_default: false,
  },
  {
    id: 1005,
    name: 'Nodirbek Vositov',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/a5/f0/8fe34ff12a28632e9673734a842f5a8d381.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'nodirbek.vositov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: true,
    has_file_access_by_default: false,
  },
  {
    id: 987,
    name: 'Oleksandr Berezhnyi',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/da/33/5de88146df37bc392439e4ced294e6db770.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'oleksandr.berezhnyi@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 975,
    name: 'Olena Borshchova',
    position: 'QA',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/0b/22/319a0eba121db26c8562cc70135fda3f374.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'olena.borshchova@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: true,
    has_file_access_by_default: false,
  },
  {
    id: 2503,
    name: 'Olga Kireeva',
    position: 'QA',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/f1/c8/fcd54c2a83f1c902c01ca57e05aecbb5645.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'olga.kireeva@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1007,
    name: 'Petar Stefanovi\u0107',
    position: 'Angular Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'petar.stefanovic@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 984,
    name: 'Sergey Romanov',
    position: 'Head of Sales',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'sergey.romanov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: true,
  },
  {
    id: 1082,
    name: 'Serhii Filatov',
    position: 'React developer',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/72/0f/6267265aa2683ece71248cfc5f49ec61446.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'serhii.filatov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 968,
    name: 'Sofiia Klymovych',
    position: 'QA',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/98/49/3e789b606822dd4a11f02926a928d49827.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'sofiia.klymovych@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1117,
    name: 'Svetlana Demydko',
    position: 'QA Engineer',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/05/be/ec7f9bd978171d6af76a6130812be6d8647.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'svetlana.demydko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 986,
    name: 'Tanya Chorna',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/9e/2d/46d5bc5c7442dd92d2d88d4f1f6f2350666.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'tanya.sashyna@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 4,
    name: 'Veronika Lebedinskaya',
    position: 'Recruiter',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/3f/69/aebb8a9d5a75ada30ff2b580d06ef573877.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'veronika.lebedynska@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 982,
    name: 'Vlad Ilchenko',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'vlad.ilchenko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 966,
    name: 'Vladislav Prokhorenko',
    position: 'Node.js Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/e5/b5/5c25dc6cee199ac26cc2ac6094886840278.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'vladislav.prokhorenko@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1004,
    name: 'Yakub Yakubov',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/ad/fa/1f83534083c52227ffaec04842b2d375398.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'yakub.yakubov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 1,
    name: 'Yanina Miasnykova',
    position: 'Lead of Recruitment',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/1e/39/1ce05302e435b0c892594359e3e78bf4574.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'yanina.miasnykova@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: true,
    has_file_access_by_default: true,
  },
  {
    id: 998,
    name: 'Yevhenii Sukhov',
    position: 'CTO',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/a2/0d/85f5e407585cb7efd0c81db5d03f3512616.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'yevhenii.sukhov@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: true,
  },
  {
    id: 976,
    name: 'Yuliia Klimachova',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/avatars/02/36/894155d459c8cb2af7b715320d9fab4f472.jpeg',
    is_employee: true,
    links: { self: null },
    email: 'yuliia.klimachova@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 985,
    name: 'Yurii Levandovskyi',
    position: 'Project Manager',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'Yurii.levandovskyi@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
  {
    id: 969,
    name: '\u041b\u0435\u043d\u0430 \u0411\u0438\u0440\u044e\u043a\u043e\u0432\u0430 ',
    position: 'React Dev',
    avatar_src:
      'https://hyggesoftware.hurma.work/storage/hrms/assets/img/avatar/employee/employee-empty-avatar.svg',
    is_employee: true,
    links: { self: null },
    email: 'lena.biriukova@hygge.software',
    can_create_hr_actions: false,
    is_current_user: false,
    has_google_account: false,
    has_file_access_by_default: false,
  },
];
